playlist/config/routes.rb
Playlist::Application.routes.draw do
  get "manager/index"
  post "manager/show"
  post "manager/find"
  get "home_page/index"
  post "home_page/list"
  post "home_page/find"
  post "home_page/show"
  resources :songs
  root :to => 'home_page#index' 

  

end

playlist/app/models/song.rb
class Song < ActiveRecord::Base
		attr_accessible  :name, :artist, :album, :image, :link
		validates  :name, :artist, :album, :image, :link, :presence => true
		validates :image, :uniqueness => false	
		validates :link, :uniqueness => true
       end

playlist/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

playlist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

playlist/app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end

  def list
  	@songs = Song.all
  end

  def find
	@params = params[:song]
	@song = Song.find_by_name (@params[:name])

	respond_to do |format|
	if @song != nil
		format.html {render :action => :show}
	else
		format.html { render :action => :not_found }	
			end
		end
	end


	def show
	id = params[:item][:id]
	@song = Song.find(id)

	respond_to do |format|
	if @song != nil
		format.html
	else
		format.html{render :action => "not_found"}
			end
		end
	end

end

playlist/app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  def index
  end

  def show
	@params = params[:song]
	@song = Song.find_by_name (@params[:name])

	respond_to do |format|
	if @song != nil
		format.html
	else
		format.html { render :action => "not_found" }	
		end
	 end
  end


  def find
	@params = params[:song]
	@song = Song.find_by_name (@params[:name])

	respond_to do |format|
	if @song != nil
		format.html {render :action => :show}
	else
		format.html { render :action => :not_found }	
			end
		end
	end

	def find_by_artist
	@params = params[:song]
	@song = Song.find_by_artist (@params[:artist])

	respond_to do |format|
	if @song != nil
		format.html {render :action => :show}
	else
		format.html { render :action => :not_found }	
			end
		end
	end

end

playlist/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to (manager_index_url) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist, :album, :image, :link)
    end
end

playlist/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

playlist/app/helpers/application_helper.rb
module ApplicationHelper
end

playlist/app/helpers/home_page_helper.rb
module HomePageHelper
end

playlist/app/helpers/manager_helper.rb
module ManagerHelper
end

playlist/app/helpers/songs_helper.rb
module SongsHelper
end

playlist/app/helpers/users_helper.rb
module UsersHelper
end

playlist/app/views/home_page/index.html.erb
<h1>Music Playlist</h1>
<h2>List all songs</h2>
 			<h3><%= form_for  :song,  :url => {:action => :list} do |form| %>
 			<p><%= submit_tag   "List Songs" %></p></h3>
<% end %>
<h2>Find a song</h2>
<h3><%= form_for  :song, :url => {:action => :find} do |form| %>
<p><label for="title">Name:</label>
<%= form.text_field  :name, :size => 20 %></p>
<p><%= submit_tag   "Find a Song" %></p></h3>

<h3> Listen to your Playlist: </h3>
<h3> <a href = "http://www.youtube.com/watch?v=2u_YrOtAXFY&list=PLnZC4_ie0EuMJ6ASW-gkBPURP1z-y6ktL">Click Me!</a>
<% end %>

playlist/app/views/home_page/list.html.erb
<h1>Song Listing</h1>
<table>
<tr>
<th>Image</th>
<th>Name</th>
<th>Artist</th>
<th>Album</th>
<th></th>
</tr>	
<% @songs.each do |song| %>
<tr>
<td><%= image_tag song.image %></td>
<td><%= song.name %></td>
<td><%= song.artist %></td>
<td><%= song.album %></td>
<td><%= form_for :item, :url => {:action => :show} do |form| %>
<%= form.hidden_field :id, :value => song.id  %>
<p><%= submit_tag "Show" %></p>
<% end %>
</td> 
</tr>
<% end %>
</table>

<p><%= link_to 'Back', home_page_index_path %></p>

playlist/app/views/home_page/not_found.html.erb
<h3>Song not found.</h3>

<h3>Add to your Playlist?</h3>
	<%= link_to  'New Song',  new_song_path %> <br />

<h3> Or, go back? </h3>

<%= link_to 'Back', home_page_index_path %>

playlist/app/views/home_page/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
	<strong>Image:</strong>
	<%= image_tag @song.image %>
</p>


<%= link_to 'Back', home_page_index_path %>

playlist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

playlist/app/views/manager/find.html.erb
<table class="center">
<tr>
<th>ID</th>
<th>Image</th>
<th>Name</th>
<th>Artist</th>
<th>Album</th>
<th></th>
<th></th>
<th></th>
</tr>

<tr>
<td><%= @song.id %></td>
<td><%= @song.image %></td>
<td><%= @song.name %></td>
<td><%= @song.artist %></td>
<td><%= @song.album %></td>
<td><%= link_to 'Show', @song %></td>
<td><%= link_to 'Edit', edit_product_path(@song) %></td>
<td><%= link_to 'Destroy', @song, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>
</table>

<br />
<%= link_to 'Back', manager_index_path %>

playlist/app/views/manager/index.html.erb
<h1>Manager’s Page</h1>

<h2>Show</h2>
<h3><%= form_for  :song,  :url => {:action => :show}  do |form| %>
<p><label for="title">Name:</label>
<%= form.text_field  :name,  :size => 20 %></p>
<p><%= submit_tag "Show" %></p></h3>
<% end %>

<h2>Find by Name</h2>
<h3><%= form_for  :song, :url => {:action => :find} do |form| %>
<p><label for="title">Name:</label>
<%= form.text_field  :name, :size => 20 %></p>
<p><%= submit_tag   "Find" %></p></h3>
<% end %>

<h3> Listen to your Playlist: </h3>
<h3> <a href = "http://www.youtube.com/watch?v=2u_YrOtAXFY&list=PLnZC4_ie0EuMJ6ASW-gkBPURP1z-y6ktL">Click Me!</a>

<h2>New</h2>
	<%= link_to  'New Song',  new_song_path %>

<h2>Home Page</h2>
<%=link_to  'Home Page',  home_page_index_path%>

playlist/app/views/manager/not_found.html.erb
<h3>Song not found.</h3>
<%= link_to 'Back', manager_index_path %>

playlist/app/views/manager/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
	<strong>Image:</strong>
	<%= image_tag @song.image %>
</p>
<p>
	<strong>ID:</strong>
	<%= @song.id %>
</p>



<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back',  manager_index_path %>

playlist/app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="field">
  <%= f.label :image %><br />
  <%= f.text_field :image %>
  </div>
  <div class="field">
	<%= f.label :link %><br>
	<%= f.text_field :link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

playlist/app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

playlist/app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Image</th>
      <th>Link</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.artist %></td>
        <td><%= song.album %></td>
        <td><%= image_tag song.image %></td>
		<td><a href=<%= song.link %>> Click Here </a></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

playlist/app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

playlist/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
	<strong>Image:</strong>
	<%= image_tag @song.image %>
</p>

<p>
	<b>Link: </b>
	<%= @song.link %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

playlist/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

playlist/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

playlist/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

playlist/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

playlist/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>